Repository DrewThomasson/ebook2audiobook, pull requests merged in 2025-01, with the labels that each got.

#172 Added details about how to build and making the xtts model baked in d…
  Dockerfile
  README.md
Labels: docker

#175 Create an Arabic README file
  README.md
  readme/README_AR.md
Labels: documentation

#233 Update requirements.txt
  ebook2audiobookXTTS.egg-info/requires.txt
  pyproject.toml
  requirements.txt
Labels: bug
